[2025-10-16T12:48:54.062+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T12:48:54.123+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T12:48:54.138+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T12:48:54.180+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T12:48:54.268+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T13:32:34.482+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T13:32:34.583+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T13:32:34.648+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T13:32:34.697+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T13:32:35.225+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T13:37:34.977+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T13:37:35.075+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T13:42:35.863+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T13:42:36.067+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T13:47:38.248+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T13:47:43.659+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T13:56:07.869+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T13:56:09.153+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:01:08.752+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:01:08.803+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:04:04.850+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T14:04:05.949+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T14:04:06.643+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T14:04:06.864+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:04:07.772+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:04:22.393+0000] {manager.py:833} ERROR - Error removing old import errors
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 829, in _refresh_dag_dir
    DagFileProcessorManager.clear_nonexistent_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 899, in clear_nonexistent_import_errors
    session.execute(query.execution_options(synchronize_session="fetch"))
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-16T14:14:45.119+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T14:14:45.165+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T14:14:45.166+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T14:14:45.168+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:14:45.485+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:19:45.881+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:19:46.066+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:34:03.854+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T14:34:03.863+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T14:34:03.864+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T14:34:03.867+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:34:03.900+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:43:23.925+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:43:25.458+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:46:56.669+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T14:46:56.689+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T14:46:56.708+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T14:46:56.714+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:46:56.749+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T14:59:32.887+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T14:59:32.901+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T14:59:32.903+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T14:59:32.919+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T14:59:32.973+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T15:04:33.638+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T15:04:33.760+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T15:09:34.262+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T15:09:34.404+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T15:19:31.594+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T15:20:21.997+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T15:36:16.896+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T15:36:18.791+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T15:36:31.116+0000] {manager.py:833} ERROR - Error removing old import errors
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 659, in get_connection
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 829, in _refresh_dag_dir
    DagFileProcessorManager.clear_nonexistent_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 899, in clear_nonexistent_import_errors
    session.execute(query.execution_options(synchronize_session="fetch"))
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    dbapi_connection = rec.get_connection()
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 659, in get_connection
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-16T15:43:47.071+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T15:43:47.282+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T15:43:47.310+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T15:43:47.356+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T15:43:47.547+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-16T15:54:10.810+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-16T15:54:10.816+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-16T15:54:10.818+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-16T15:54:10.821+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-16T15:54:10.985+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-17T15:23:33.442+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-17T15:23:33.510+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-17T15:23:33.516+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-17T15:23:33.518+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-17T15:23:33.563+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-17T15:29:45.289+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-17T15:29:46.481+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-17T15:34:45.610+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-17T15:34:46.076+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-17T15:39:50.498+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-17T15:39:55.222+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-18T09:54:05.708+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-18T09:54:05.715+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-18T09:54:05.719+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-18T09:54:05.720+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-18T09:54:05.747+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-18T10:03:38.945+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-18T10:03:38.964+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-18T10:03:38.978+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-18T10:03:39.017+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-18T10:03:39.137+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-18T10:10:24.746+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-18T10:10:25.779+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-18T10:15:24.849+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-18T10:15:25.090+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T07:40:22.965+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T07:40:23.046+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T07:40:23.119+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T07:40:23.231+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T07:40:23.741+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T07:45:23.443+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T07:45:24.853+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T09:34:16.353+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T09:34:16.461+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T09:34:16.535+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T09:34:16.635+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T09:34:18.569+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T09:39:16.911+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T09:39:17.061+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T09:44:17.104+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T09:44:18.964+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T09:49:17.956+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T09:49:22.503+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T09:54:18.070+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T09:54:18.528+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T10:00:02.583+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T10:00:03.841+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T11:09:54.265+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T11:09:54.278+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T11:09:54.296+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T11:09:54.313+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T11:09:54.937+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T11:50:55.726+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T11:50:55.740+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T11:50:55.743+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T11:50:55.745+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T11:50:55.881+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T12:15:09.427+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T12:15:09.488+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T12:15:09.534+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T12:15:09.552+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T12:15:09.708+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T13:07:35.184+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T13:07:35.187+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T13:07:35.200+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T13:07:35.205+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T13:07:35.232+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T13:13:15.858+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T13:13:37.718+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T13:13:41.390+0000] {manager.py:465} INFO - Exiting gracefully upon receiving signal 15
[2025-10-19T13:15:33.085+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T13:15:33.102+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T13:15:33.111+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T13:15:33.119+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T13:15:33.157+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T13:15:43.626+0000] {manager.py:465} INFO - Exiting gracefully upon receiving signal 15
[2025-10-19T13:16:18.467+0000] {manager.py:483} INFO - Processing files using up to 2 processes at a time 
[2025-10-19T13:16:18.475+0000] {manager.py:484} INFO - Process each file at most once every 30 seconds
[2025-10-19T13:16:18.479+0000] {manager.py:485} INFO - Checking for new files in /opt/airflow/dags every 300 seconds
[2025-10-19T13:16:18.491+0000] {manager.py:821} INFO - Searching for files in /opt/airflow/dags
[2025-10-19T13:16:18.526+0000] {manager.py:824} INFO - There are 0 files in /opt/airflow/dags
[2025-10-19T13:16:32.959+0000] {manager.py:465} INFO - Exiting gracefully upon receiving signal 15
