[2025-10-29T11:56:35.485+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:56:35.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T11:56:35.506+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:35.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:56:36.342+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:56:38.748+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:38.746+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:fraud_detection_training
[2025-10-29T11:56:38.803+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:38.801+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:fraud_detection_training
[2025-10-29T11:56:38.857+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:38.856+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:fraud_detection_training
[2025-10-29T11:56:38.922+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:38.921+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:fraud_detection_training
[2025-10-29T11:56:38.984+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:38.983+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:fraud_detection_training
[2025-10-29T11:56:39.038+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:39.038+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:fraud_detection_training
[2025-10-29T11:56:39.131+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:39.129+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:fraud_detection_training
[2025-10-29T11:56:39.141+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:39.140+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T11:56:39.325+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:39.324+0000] {dag.py:3262} INFO - Creating ORM DAG for fraud_detection_training
[2025-10-29T11:56:39.500+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:56:39.490+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T11:56:39.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 4.314 seconds
[2025-10-29T11:57:10.494+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:57:10.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T11:57:10.508+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:57:10.507+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:57:10.940+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:57:11.091+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:57:11.090+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T11:57:11.290+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:57:11.289+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T11:57:11.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 0.832 seconds
[2025-10-29T11:57:42.513+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:57:42.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T11:57:42.535+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:57:42.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:57:42.814+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:57:43.359+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:57:43.358+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T11:57:43.961+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:57:43.960+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T11:57:44.116+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 1.636 seconds
[2025-10-29T11:58:14.826+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:58:14.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T11:58:14.990+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:58:14.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:58:20.955+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T11:58:21.999+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:58:21.998+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T11:58:45.283+0000] {logging_mixin.py:190} INFO - [2025-10-29T11:58:45.133+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T11:59:01.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 43.567 seconds
[2025-10-29T12:00:00.632+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:00:01.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:00:02.604+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:00:01.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:01:12.547+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:00:43.579+0000] {timeout.py:68} ERROR - Process timed out, PID: 126
[2025-10-29T12:08:20.940+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:01:46.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/fraud_detection_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 100, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 683, in __init__
    elif isinstance(schedule, Collection) and not isinstance(schedule, str):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/typing.py", line 1221, in __instancecheck__
    def __instancecheck__(self, obj):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/fraud_detection_training_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#reducing-dag-complexity, PID: 126
[2025-10-29T12:08:21.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:10:40.193+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:10:40.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:10:40.858+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:10:40.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:10:57.551+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:10:56.951+0000] {variable.py:357} ERROR - Unable to retrieve variable from secrets backend (MetastoreBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 353, in get_variable_from_secrets
    var_val = secrets_backend.get_variable(key=key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/metastore.py", line 66, in get_variable
    return MetastoreBackend._fetch_variable(key=key, session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/metastore.py", line 84, in _fetch_variable
    var_value = session.scalar(select(Variable).where(Variable.key == key).limit(1))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-29T12:10:59.223+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:11:23.243+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:11:23.235+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T12:11:58.711+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:11:58.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:11:58.805+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:11:58.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:12:02.784+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:12:04.551+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:12:04.550+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T12:12:05.748+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:12:05.736+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T12:12:06.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 8.670 seconds
[2025-10-29T12:12:37.730+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:12:37.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:12:37.754+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:12:37.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:12:38.189+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:12:38.502+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:12:38.493+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T12:12:38.884+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:12:38.883+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T12:12:39.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 1.491 seconds
[2025-10-29T12:13:09.589+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:13:09.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:13:09.651+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:13:09.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:13:10.102+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:13:10.483+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:13:10.482+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T12:13:10.646+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:13:10.645+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T12:13:10.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 1.343 seconds
[2025-10-29T12:13:42.001+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:13:42.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:13:42.118+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:13:42.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:13:42.725+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:13:44.800+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:13:44.799+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T12:13:45.143+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:13:45.143+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T12:13:45.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 3.752 seconds
[2025-10-29T12:14:23.131+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:14:23.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:14:23.428+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:14:23.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:14:33.486+0000] {processor.py:925} INFO - DAG(s) 'fraud_detection_training' retrieved from /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:14:39.078+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:14:39.075+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-29T12:14:54.319+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:14:54.318+0000] {dag.py:4180} INFO - Setting next_dagrun for fraud_detection_training to 2025-10-28 03:00:00+00:00, run_after=2025-10-29 03:00:00+00:00
[2025-10-29T12:14:55.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/fraud_detection_training_dag.py took 32.829 seconds
[2025-10-29T12:15:58.724+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/fraud_detection_training_dag.py
[2025-10-29T12:15:59.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/fraud_detection_training_dag.py for tasks to queue
[2025-10-29T12:16:04.741+0000] {logging_mixin.py:190} INFO - [2025-10-29T12:15:59.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/fraud_detection_training_dag.py
